steps:
  - name: node:20
    env:
      - ID=${_ID}
    args:
      - /build/index.js
    entrypoint: node
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - "-c"
      - |
        echo "Listing workspace files:"
        ls -R /workspace
    entrypoint: bash
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - app
      - deploy
      - "--quiet"
    entrypoint: gcloud
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
