# Use official Node.js 20 Alpine image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy repo contents
COPY . .

# Build-time argument for client ID
ARG ID
ENV ID=${ID}

# Optional: set default NAME environment (will be overwritten in build script)
ENV NAME=unknown

# Debug
RUN echo "Building with ID=$ID"

# Run the build script that generates:
# - package.json
# - router/index.js
# - Dockerfile (optional)
RUN node build/index.js

# Install dependencies (package.json generated by build script)
RUN npm install --omit=dev

# Expose port
ENV PORT=3000
EXPOSE 3000

# Start the app
CMD ["node", "index.js"]
