# Use official Node.js 20 LTS Alpine image
FROM node:20-alpine

WORKDIR /app

# Copy everything first (including build folder)
COPY . .

# Debug: verify files
RUN ls -la /app
RUN ls -la /app/build

# 1️⃣ Run the build script that generates package.json, Dockerfile, etc.
RUN node build/index.js

# 2️⃣ Install dependencies now that package.json exists
RUN npm install --omit=dev

# 3️⃣ Read client.name and set as ENV
# This reads the CLIENT_NAME file generated by the build script
RUN export NAME=$(cat /app/CLIENT_NAME) && echo "NAME=$NAME" > /etc/build_env

# 4️⃣ Expose port and environment
ENV PORT=3000
# Load NAME from previous step
ENV NAME=$(cat /app/CLIENT_NAME)

EXPOSE 3000

# 5️⃣ Start the app
CMD ["node", "index.js"]
