services:
  - type: web
    name: ${CLIENT_NAME}       # Uses CLIENT_NAME env variable
    env: docker
    plan: starter
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: ID
        value: ${CLIENT_NAME}          # Uses ID env variable

    healthCheckPath: /